### PR TITLE
Fix wrong args of cert-manager

### PR DESCRIPTION
**Pull request by bincherry**
#### What type of PR is this?

/kind bug

#### Special notes for your reviewer

`--enable-certificate-owner-ref` is an arg for cert-manager controller, not for cert-manager-cainjector

> https://cert-manager.io/docs/cli/controller/
> https://cert-manager.io/docs/cli/cainjector/

### CODE REVIEW

**Comment by Abirdcfly** [comment]
the chart version should be updated, too.

**Comment by bjwswang** [comment]
@bincherry Thanks! Please fix the lint test

**Comment by bjwswang** [comment]
@bincherry btw... is that possible to merge  cluster-component and u4a-component  ?

**Review by bjwswang — APPROVED** [review]
LGTM

**Pull request merged**
